#配置端口号
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka #Eureka Server查询注册地址
    register-with-eureka: false

